### ISSUE TITLE
How can I tell what version of CalculiX the ppd is using?

### ISSUE THREAD

**Issue by luzpaz** [ppd/freecad-ppd#31]
I see it getting pulled in via https://github.com/ppd/freecad-ppd/blob/master/snap/snapcraft.yaml#L200

**Comment by ppd** [comment]
It is pulled from the core20 repositories. Core20 = Ubuntu 20.04. So it should be https://ubuntu.pkgs.org/20.04/ubuntu-universe-amd64/calculix-ccx_2.11-1build3_amd64.deb.html

**Comment by luzpaz** [comment]
Thanks and Yikes! Do you happen to know when Ubuntu pulls in Debian package updates? I recently was successful in getting a Debian Science maintainer to bump the experimental (sid) repo with Calculix v2.19  
https://salsa.debian.org/science-team/calculix-ccx/-/commit/4fbb7fd721c285fb9e96129fe1c2ead4644db4ac

**Comment by ppd** [comment]
I have no experience in this area. I think someone needs to file a sync request via launchpad: https://wiki.ubuntu.com/SyncRequestProcess

In the snap case, any such sync would be too late for the next base, core22, anyway. It's probably better to build such high-level dependencies in the Flatpaks, Snaps et al. instead of relying on the repositories.
